# Generated by Django 3.1.5 on 2021-07-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('history', 'history'), ('romance', 'romance'), ('marathi', 'Marathi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('hindi', 'hindi'), ('marathi', 'Marathi')], max_length=50),
        ),
    ]
